### ISSUE TITLE
Unfired Prospector's Hammer Head Mold (Precision Prospecting) recipe conflicts with Unfired Sledgehammer Head Mold recipe

### ISSUE THREAD

**Issue by Quizer9O8** [RTCornejo/TFC-Hammer_Time#2]
The mold recipe for the Unfired Prospector's Hammer Head Mold from the mod **[Precision Prospecting](https://www.curseforge.com/minecraft/mc-mods/precision-prospecting)** overrides that of the Unfired Sledgehammer Head Mold recipe since they both use the exact clay knapping recipe.

**Unfired Prospector's Hammer Head Mold** (Precision Prospecting)
![image](https://github.com/user-attachments/assets/4b44187e-0542-48f6-afb0-4f88a82060ae)

**Unfired Sledgehammer Head Mold**
![image](https://github.com/user-attachments/assets/245b938c-5a84-4f6d-84d1-1d6abea41d25)

You might want to use an alternative clay knapping recipe if both mods are present or just change the clay knapping recipe altogether.

**Comment by RTCornejo** [comment]
![522268cf37974c41b8f29bde40a23bb3fb61c970](https://github.com/user-attachments/assets/b994789d-d7d0-409f-9033-f4fa32034d23)
Hope this one's better
